/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Game.View;

/**
 *
 * @author vansh
 */
public class TournamentView extends javax.swing.JFrame {
     /**
     * Creates new form NewJFrame
     */
    public TournamentView  () {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        Game1_Log_Button = new javax.swing.JButton();
        Game2_Log_Button = new javax.swing.JButton();
        Game3_Log_Button = new javax.swing.JButton();
        Game4_Log_Button = new javax.swing.JButton();
        Game5_Log_Button = new javax.swing.JButton();
        Game6_Log_Button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tournament_Game_Log_jlist = new javax.swing.JList<>();
        Game7_Log_Button = new javax.swing.JButton();
        Game8_Log_Button = new javax.swing.JButton();
        Game9_Log_Button = new javax.swing.JButton();
        Game10_Log_Button = new javax.swing.JButton();
        Game11_Log_Button = new javax.swing.JButton();
        Game12_Log_Button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Game1_Log_Button.setText("Game 1");

        Game2_Log_Button.setText("Game 2");

        Game3_Log_Button.setText("Game 3");

        Game4_Log_Button.setText("Game 4");

        Game5_Log_Button.setText("Game 5");

        Game6_Log_Button.setText("Game 6");

        jLabel1.setText("      GAME LOG");

        jScrollPane1.setViewportView(Tournament_Game_Log_jlist);

        Game7_Log_Button.setText("Game 7");

        Game8_Log_Button.setText("Game 8");

        Game9_Log_Button.setText("Game 9");

        Game10_Log_Button.setText("Game 10");

        Game11_Log_Button.setText("Game 11");

        Game12_Log_Button.setText("Game 12");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Game6_Log_Button)
                        .addGap(43, 43, 43)
                        .addComponent(Game12_Log_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Game1_Log_Button)
                        .addGap(43, 43, 43)
                        .addComponent(Game7_Log_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Game2_Log_Button)
                        .addGap(43, 43, 43)
                        .addComponent(Game8_Log_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Game3_Log_Button)
                        .addGap(43, 43, 43)
                        .addComponent(Game9_Log_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Game4_Log_Button)
                        .addGap(43, 43, 43)
                        .addComponent(Game10_Log_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Game5_Log_Button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Game11_Log_Button)))
                .addGap(97, 97, 97)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(239, 239, 239))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Game1_Log_Button)
                            .addComponent(Game7_Log_Button))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Game2_Log_Button)
                            .addComponent(Game8_Log_Button))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Game3_Log_Button)
                            .addComponent(Game9_Log_Button))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Game4_Log_Button)
                            .addComponent(Game10_Log_Button))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Game5_Log_Button)
                            .addComponent(Game11_Log_Button))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Game6_Log_Button)
                            .addComponent(Game12_Log_Button)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
     

    // Variables declaration - do not modify                     
    private javax.swing.JButton Game10_Log_Button;
    private javax.swing.JButton Game11_Log_Button;
    private javax.swing.JButton Game12_Log_Button;
    private javax.swing.JButton Game1_Log_Button;
    private javax.swing.JButton Game2_Log_Button;
    private javax.swing.JButton Game3_Log_Button;
    private javax.swing.JButton Game4_Log_Button;
    private javax.swing.JButton Game5_Log_Button;
    private javax.swing.JButton Game6_Log_Button;
    private javax.swing.JButton Game7_Log_Button;
    private javax.swing.JButton Game8_Log_Button;
    private javax.swing.JButton Game9_Log_Button;
    private javax.swing.JList<String> Tournament_Game_Log_jlist;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration                   
}


